### ISSUE TITLE
Réduire la taille du site compilé 

### ISSUE THREAD

**Issue by ZakCodes** [cyberquebec-org/cyberquebec-org.github.io#1]
En ce moment, lorsque le site est compilé, tout le repository de FontAwesome est inclus dans le résultat.  
Pour remédier à cela, j'ai testé ces configurations: 
```yml
exclude: 
  - assets/fontawesome
include: 
  - assets/fontawesome/css
```
et
```yml
exclude: 
  - assets/fontawesome/*
include: 
  - assets/fontawesome/css/*
```
mais aucune ne fonctionne.  

Cela est du au fait que, comme mentionné dans jekyll/jekyll#4791, l'exclusion a priorité sur l'inclusion.  
Cet issue n'est probablement pas si compliqué à régler, mais la modification ne peut pas être faite avant Jekyll 4.0, car certains sites pourraient être brisés par cette modification.
